name: Outputs test

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  job-1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output-1: ${{ steps.step-1.outputs.test-test }}
      output-2: ${{ steps.step-2.outputs.test-test }}
    steps:
      - id: step-1
        run: echo "test-test=hello" >> "$GITHUB_OUTPUT"
      - id: step-2
        run: echo "test-test=world" >> "$GITHUB_OUTPUT"
  job-2:
    runs-on: ubuntu-latest
    if: ${{needs.job-1.outputs.output-1 == 'hello'}}
    needs: job-1
    steps:
      - env:
          OUTPUT1: ${{needs.job-1.outputs.output-1}}
          OUTPUT2: ${{needs.job-1.outputs.output-2}}
        run: echo "$OUTPUT1 $OUTPUT2"
