name: redash

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  redash:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          repository: "vinodpandey/redash"
          ref: "master"

      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
