name: GitHub Action sandbox - GCP
on:
  push:
  workflow_dispatch:

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: "actions/checkout@v3"
      - run: echo ${{ secrets.SECRET_NAME }}
