name: GitHub Action sandbox - Use secret action
on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      SECRET_NAME:
        required: true
  workflow_dispatch:

jobs:
  echo-secret:
    runs-on: ubuntu-latest
    steps:
      - run: echo "github.ref=${{ github.ref }}"
      - run: echo "github.head_ref=${{ github.head_ref }}"
      # https://github.com/actions/checkout
      - uses: "actions/checkout@v3"
        with:
          ref: ${{ github.head_ref || github.ref }}
      - run: echo "${{ secrets.SECRET_NAME }}"
