name: Test

on:
  - workflow_dispatch

env:
  WORKER_COUNT: 3

jobs:
  define-matrix:
    name: define-matrix
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      worker-index: ${{ steps.calculate-worker-index.outputs.worker-index }}

    steps:
      - id: calculate-worker-index
        # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] のような配列を生成する
        run: echo "worker-index=$(echo ${{ env.WORKER_COUNT }} | jq --compact-output '[range(.)]')" >> "$GITHUB_OUTPUT"

  test:
    name: WorkerIndex(${{ matrix.worker-index }}), MySQL(${{ matrix.mysql-version }})
    runs-on: ubuntu-latest
    needs: define-matrix
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        mysql-version: ["5.7", "8.0"]
        worker-index: ${{ fromJSON(needs.define-matrix.outputs.worker-index) }}

    steps:
      - name: WorkerIndex(${{ matrix.worker-index }}), MySQL(${{ matrix.mysql-version }})
        run: echo "hello"
