name: tfmigrate

on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TERRAFORM_VERSION: latest
  TFMIGRATE_INSTALL_DIR: /tmp/tfmigrate

jobs:
  tfmigrate:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - run: terraform --version

      - name: Install tfmigrate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ${{ env.TFMIGRATE_INSTALL_DIR }}
          gh release download --repo minamijoyo/tfmigrate --pattern 'tfmigrate_*_linux_amd64.tar.gz' --output - | tar xz --directory ${{ env.TFMIGRATE_INSTALL_DIR }}
          echo ${{ env.TFMIGRATE_INSTALL_DIR }} >> $GITHUB_PATH

      - run: tfmigrate --version
